Repository gardener/image-vector, pull requests merged in 2022-02, with the labels that each got.

#4 images with no target version
  pkg/overwrite.go
Labels: needs/review, size/s

#5 expand images with no target version
  pkg/overwrite.go
Labels: reviewed/ok-to-test, needs/review, size/xs

#6 Prevent loss of target value label
  pkg/imagevector.go
  pkg/imagevector_test.go
  pkg/testdata/resources/12-multi-targetversion-same-name-and-tag.yaml
Labels: needs/ok-to-test, needs/review, size/s
